import type { Product } from '../store/store'

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Wireless Noise-Cancelling Headphones',
    price: 299.99,
    originalPrice: 399.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 124,
    description: 'Experience pure sound with industry-leading active noise cancellation. Designed for premium comfort and long-lasting performance up to 30 hours of wireless playback.',
    colors: ['#000000', '#C0C0C0', '#F5F5DC'],
    sizes: ['Standard'],
    inStock: true,
    isHot: true,
    brand: 'AudioPhile'
  },
  {
    id: '2',
    title: 'Minimalist Leather Smart Watch',
    price: 199.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    category: 'electronics',
    rating: 4.5,
    reviewsCount: 89,
    description: 'A stylish and sleek smart wearable featuring a genuine leather strap, always-on AMOLED display, comprehensive fitness tracking, and up to 7 days of battery life.',
    colors: ['#8B4513', '#000000', '#556B2F'],
    sizes: ['S', 'M', 'L'],
    inStock: true,
    isNew: true,
    brand: 'Chronos'
  },
  {
    id: '3',
    title: 'Minimalist Premium Cotton Hoodie',
    price: 79.99,
    originalPrice: 99.99,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&auto=format&fit=crop&q=80',
    category: 'clothing',
    rating: 4.7,
    reviewsCount: 230,
    description: 'Crafted from 100% heavyweight organic cotton. Featuring a relaxed fit, drop shoulders, double-layered hood, and kangaroo pocket. Ideal for effortless everyday style.',
    colors: ['#808080', '#000000', '#F5F5F5', '#4B5320'],
    sizes: ['S', 'M', 'L', 'XL'],
    inStock: true,
    brand: 'Aether'
  },
  {
    id: '4',
    title: 'Ergonomic Premium Office Chair',
    price: 449.99,
    image: 'https://images.unsplash.com/photo-1505797149-43b0069ec26b?w=600&auto=format&fit=crop&q=80',
    category: 'home',
    rating: 4.9,
    reviewsCount: 76,
    description: 'Engineered for exceptional lumbar support and airflow. Fully adjustable armrests, seat height, headrest, and recline dynamic locking system to support long working hours.',
    colors: ['#000000', '#808080'],
    sizes: ['Standard'],
    inStock: true,
    brand: 'ErgoSoft'
  },
  {
    id: '5',
    title: 'Stainless Steel Vacuum Water Bottle',
    price: 34.99,
    originalPrice: 44.99,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80',
    category: 'sports',
    rating: 4.6,
    reviewsCount: 342,
    description: 'Double-walled vacuum insulation keeps drinks cold for 24 hours or hot for 12 hours. Constructed with premium food-grade stainless steel. Leak-proof and condensation-free design.',
    colors: ['#4682B4', '#000000', '#FF2E93'],
    sizes: ['500ml', '750ml', '1L'],
    inStock: true,
    brand: 'HydroGo'
  },
  {
    id: '6',
    title: 'Professional Ceramic Hair Dryer',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&auto=format&fit=crop&q=80',
    category: 'beauty',
    rating: 4.4,
    reviewsCount: 54,
    description: 'Salon-grade hair dryer featuring negative ion ceramic technology for shiny, frizz-free hair. High-velocity motor with multiple heat and speed settings.',
    colors: ['#E6E6FA', '#000000'],
    sizes: ['Standard'],
    inStock: false,
    brand: 'Bloom'
  },
  {
    id: '7',
    title: 'Organic Lavender Scented Candle',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80',
    category: 'home',
    rating: 4.3,
    reviewsCount: 112,
    description: 'Hand-poured natural soy wax candle infused with organic lavender essential oils. Slow burning up to 50 hours. Eco-friendly cotton wick for a clean, aromatic experience.',
    colors: ['#E6E6FA'],
    sizes: ['Standard'],
    inStock: true,
    brand: 'Aroma'
  },
  {
    id: '8',
    title: 'Waterproof Lightweight Hiking Backpack',
    price: 89.99,
    originalPrice: 119.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    category: 'sports',
    rating: 4.7,
    reviewsCount: 165,
    description: 'Extremely durable, waterproof ripstop nylon backpack. Features multiple compartments, hydration bladder sleeve, padded shoulder straps, and integrated rain cover.',
    colors: ['#FF5733', '#2E4053', '#239B56'],
    sizes: ['30L', '45L'],
    inStock: true,
    brand: 'Wilderness'
  }
]
